// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcRazorLabb.Models;

namespace MvcRazorLabb.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcRazorLabb.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.R.R Tolkien",
                            IsAvailable = true,
                            Title = "Sagan om ringen"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.R.R Tolkien",
                            IsAvailable = true,
                            Title = "Sagan om de två tornen"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.R.R Tolkien",
                            IsAvailable = true,
                            Title = "Sagan om konungens återkomst"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Paulo Coelho",
                            IsAvailable = true,
                            Title = "Alkemisten"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Håkan Sundquist och Jerker Eriksson",
                            IsAvailable = true,
                            Title = "Kråkflickan"
                        });
                });

            modelBuilder.Entity("MvcRazorLabb.Models.BorrowedBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("BorrowedBooks");
                });

            modelBuilder.Entity("MvcRazorLabb.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jeremy@jerm.se",
                            FirstName = "Jeremy",
                            LastName = "Cedendahl"
                        },
                        new
                        {
                            Id = 2,
                            Email = "johan@johan.se",
                            FirstName = "Johan",
                            LastName = "Larsson"
                        },
                        new
                        {
                            Id = 3,
                            Email = "douglas@dogge.se",
                            FirstName = "Douglas",
                            LastName = "Dahlström"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sakarias@zacke.se",
                            FirstName = "Sakarias",
                            LastName = "Dahlström"
                        },
                        new
                        {
                            Id = 5,
                            Email = "josefine@fia.se",
                            FirstName = "Fia",
                            LastName = "Johansson"
                        });
                });

            modelBuilder.Entity("MvcRazorLabb.Models.BorrowedBook", b =>
                {
                    b.HasOne("MvcRazorLabb.Models.Book", "Book")
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MvcRazorLabb.Models.Customer", "Customer")
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
